### ISSUE TITLE
Codepen 제거

### ISSUE THREAD

**Issue by XiNiHa** [portone-io/developers.portone.io#408]
인터랙티브한 예제 표시를 위해 Codepen 사용 중인데, Stackblitz로 마이그레이션하든 자체구축하든 하면 사용성 개선 효과가 있을 듯함

**Comment by CirnoV** [comment]
Codepen은 이미 제거된 상태이고, 인터랙티브한 예제는 퀵 가이드 형태로 보여줄 예정입니당
