### ISSUE TITLE
개발자센터 API 문서 영역 펼치기 UI를 좀 더 해당 영역을 펼치는 듯한 느낌이 강하게 들도록 디자인 고치기

### ISSUE THREAD

**Issue by XiNiHa** [portone-io/developers.portone.io#438]
> Linear의 DX-30에서 옮겨옴

Hyeon K 의견

**Comment by CirnoV** [comment]
현재는 개발 리소스가 부족하므로 핵심 작업에 집중하고, 장기적으로 [Cloudflare API 문서](https://developers.cloudflare.com/api-next/resources/rulesets/methods/create/) 와 유사한 형태의 UI로 변경하려고 합니다.
