### ISSUE TITLE
script 대신 npmrc에서 NODE_OPTIONS를 설정하도록 개선

### ISSUE THREAD

**Issue by CirnoV** [portone-io/developers.portone.io#463]
앗 이걸 달려고 했는데 머지가 빠르시군요 :joy: 혹시 수정해서 올려주실래요? https://pnpm.io/npmrc#node-options

_Originally posted by @XiNiHa in https://github.com/portone-io/developers.portone.io/issues/462#issuecomment-2109304774_

**Comment by CirnoV** [comment]
이거 한번 해봤는데 모든 pnpm 스크립트에 적용돼서 astro 관련 스크립트가 다 오류가 나네요 🤔

**Comment by XiNiHa** [comment]
앗 일괄적으로 적용해도 상관없지 않을까 싶었는데 그런 문제가..... 그냥 원래대로 하는 게 나으려나 싶기도 하네요

**Comment by CirnoV** [comment]
네. 제가 생각하기에도 ts-node가 필요한건 eslint를 실행할 때 뿐이어서 기존 방식도 문제 없을 것 같아요
